name: Deploy Project
on:
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:
jobs:
  lint:
    # Notice: ubuntu runner comes with node.js pre installed
    runs-on: ubuntu-latest
    steps:
      # download the code from the repository
      - name: Get code
        uses: actions/checkout@v4
      # To fix a node.js version
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: "18"
      - name: info on kind of event triggering the workflow
        run: echo '${{ toJSON(github.event) }}'
      - name: install dependencies
        run: npm ci # to ensure you don't install some breaking versions
      - name: run linter
        run: npm run lint
  test:
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      # download the code from the repository
      - name: Get code
        uses: actions/checkout@v4
      # To fix a node.js version
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: "18"
      - name: install dependencies
        run: npm ci # to ensure you don't install some breaking versions
      - name: Run tests
        run: npm test
      - name: Build code
        run: npm run build
  deploy:
    # to run the deployment only when the test job is successful...
    needs: [lint, test] # array of jobs to wait for
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      # To fix a node.js version
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: "18"
      - name: install dependencies
        run: npm ci # to ensure you don't install some breaking versions
      - name: Build project
        run: npm run build
      - name: Deploy
        run: echo "Deploying project..."
