name: First Workflow
on: workflow_dispatch
jobs:
  # your own job name
  first-job:
    runs-on: ubuntu-latest
    steps:
      # name step to have multi-line step
      - name: Hello and Good Bye
        run: |
          echo "Hello World"
          echo "Good Bye"
